# Encoding

In [5]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data.csv')
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)

In [3]:
df

employee_id experience_level   department preferred_tools  \
0             1     Intermediate  Engineering           Slack   
1             2           Expert    Marketing           Slack   
2             3         Advanced  Engineering            Zoom   
3             4     Intermediate        Sales           Teams   
4             5            Entry    Marketing           Teams   
..          ...              ...          ...             ...   
95           96     Intermediate    Marketing     Google Meet   
96           97     Intermediate           HR     Google Meet   
97           98     Intermediate  Engineering           Teams   
98           99            Entry        Sales     Google Meet   
99          100            Entry    Marketing           Slack   

    productivity_score has_worked_before  
0                78.52               Yes  
1                87.68                No  
2                77.55               Yes  
3                75.19               Yes  
4                70.24               Yes  
..                 ...               ...  
95               69.75               Yes  
96               69.70               Yes  
97               71.10               Yes  
98               55.38               Yes  
99               72.05               Yes  

[100 rows x 6 columns]

In [11]:
x = df.iloc[:, 1:2]
y = df.iloc[:, -1]
z = df.iloc[:, 2:3]

In [12]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder

In [14]:
ordinal = OrdinalEncoder(categories=[["Entry", "Intermediate", "Advanced", "Expert"]])
x = ordinal.fit_transform(x)
x


array([[1.],
       [3.],
       [2.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [1.],
       [2.],
       [0.],
       [3.],
       [2.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [3.],
       [3.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [3.],
       [0.],
       [2.],
       [1.],
       [1.],
       [1.],
       [0.],
       [3.],
       [2.],
       [3.],
       [2.],
       [1.],
       [3.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [3.],
       [2.],
       [0.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],

In [15]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

In [16]:
y

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
one_hot = OneHotEncoder()
z = one_hot.fit_transform(z).toarray()
z

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
